# -*- coding: utf-8 -*-
"""Introduction to Machine Learning Classifiers - 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pfM2rAdcB5-Nra9x39ZX43qyDb4znjqt
"""

# hairy, short legs, woof
# 0 => NO, 1 => YES
pig1 = [0, 1, 0]
pig2 = [0, 1, 1]
pig3 = [1, 1, 0]

dog1 = [0, 1, 1]
dog2 = [1, 0, 1]
dog3 = [1, 1, 1]

# 1 => PIG
# 0 => DOG
train_x = [pig1, pig2, pig3, dog1, dog2, dog3]
train_y = [1, 1, 1, 0, 0, 0] # labels

from sklearn.svm import LinearSVC

model = LinearSVC()
model.fit(train_x, train_y)

mistery_animal = [1,1,1]
model.predict([mistery_animal])

mistery1 = [1,1,1]
mistery2 = [1,1,0]
mistery3 = [0,1,1]

test_x = [mistery1, mistery2, mistery3]
predictions = model.predict(test_x)

test_y = [0, 1, 1]

correct = (predictions == test_y).sum()
total = len(test_y)
print("Accuracy: ", correct / total * 100)

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(test_y, predictions) * 100
print("Accuracy %.2f"% accuracy)

