# -*- coding: utf-8 -*-
"""Introduction to Machine Learning - 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1femZm6uBR1H75XvsBQdtSuXQcFqZazSG
"""

!pip install seaborn==0.9.0

import pandas as pd

uri = "https://gist.githubusercontent.com/guilhermesilveira/1b7d5475863c15f484ac495bd70975cf/raw/16aff7a0aee67e7c100a2a48b676a2d2d142f646/projects.csv"
data  = pd.read_csv(uri)
data.head()

swap = {
    0 : 1,
    1 : 0
}
data['finished'] = data.unfinished.map(swap)
data.head()

data.tail()

data.finished.hist()

import seaborn as sns

sns.scatterplot(x="expected_hours",y="price",data=data)

sns.scatterplot(x="expected_hours",y="price",
                hue="finished",
                data=data)

